### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by jume-dev** [piktur/vue-cli-plugin-e2e-webdriverio#7]
Hi
did you by any chance got ES6 working?
I have tried several ways of getting babel to compile my specs but I can't seem make it work without breaking unit tests and/or serve

**Comment by diachedelic** [comment]
Are you sure you need babel? Have you tried using the latest node, plus `*.mjs` file ext if youre using es6 modules?

**Comment by jume-dev** [comment]
No, I did not try that yet. I am unsure if this feature is there to stay and also I dislike the m.
Is there really no other way?

**Comment by diachedelic** [comment]
Interoperability between commonjs and ES6 modules [has issues](https://medium.com/@dlmanning/interoperability-between-es-modules-and-common-js-is-a-mistake-fb9ac71d96fd), and you can't expect them to be resolved in the near future.  The `*.mjs` extension is a good thing, and [workbox uses it](https://github.com/GoogleChrome/workbox/tree/master/packages/workbox-core), so I don't imagine it's going to be removed any time soon.  And anyway, renaming a file extension is a lot less work than configuring babel.

**Comment by jume-dev** [comment]
Alright, thanks for your insight :)

**Comment by piktur** [comment]
@jume-dev Just adding to this, you may've read https://webdriver.io/docs/babel.html. You may also want to place `/test` only config within `/test/.babelrc` per https://babeljs.io/docs/en/config-files#file-relative-configuration.

**Comment by jume-dev** [comment]
@piktur Sadly this didn't work, but thanks for the idea.

**Comment by piktur** [comment]
@jume-dev could you share your repo? I'll take a look.

**Comment by piktur** [comment]
@jume-dev put https://github.com/piktur/vue-babel-wdio-config together for my own curiosity. Overrides babel options for files under /tests/e2e allowing one to use es6 modules.

**Comment by jume-dev** [comment]
Thanks for that man, you're a genius. 

I think I was missing the test Parameter in the babel config.

I'll give it a try in my repo (which is sadly closed source, so I can't share it)
